### ISSUE TITLE
Helm operator container segfault

### ISSUE THREAD

**Issue by aditsachde** [fluxcd/helm-operator#361]
**Describe the bug**
Helm operator container segfaults. Seems to be due to `/tmp` being unwritable, but not really sure. Tried using 1.0.0-rc7 and -rc8, same deal. I have a pod security policy where the only constraint is that it requires all pods to run with `fsGroup` as `1111:1111` but not sure if that would be causing an issue. 

Not sure if this is actually an issue with the helm operator itself, but I don't know enough about kubernetes or containers to actually debug it. Happy to provide any other information that I missed.

**To Reproduce**
Create k3s cluster, install helm, add fluxcd helm repository, create fluxcd namespace. Deploy operator using following command

```
helm upgrade -i helm-operator fluxcd/helm-operator --wait \
--namespace fluxcd \
--set git.ssh.secretName=flux-git-deploy \
--set helm.versions=v3
```

**Expected behavior**
Operator should watch for updates and deploy the charts.

**Logs**
```
W0405 03:20:50.070997       8 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ts=2020-04-05T03:20:50.075405978Z caller=operator.go:98 component=operator info="setting up event handlers"
ts=2020-04-05T03:20:50.075478429Z caller=operator.go:117 component=operator info="event handlers set up"
ts=2020-04-05T03:20:50.075557199Z caller=main.go:280 component=helm-operator info="waiting for informer caches to sync"
ts=2020-04-05T03:20:50.175929708Z caller=main.go:285 component=helm-operator info="informer caches synced"
ts=2020-04-05T03:20:50.176255536Z caller=operator.go:129 component=operator info="starting operator"
ts=2020-04-05T03:20:50.176307322Z caller=operator.go:131 component=operator info="starting workers"
ts=2020-04-05T03:20:50.176739538Z caller=server.go:42 component=daemonhttp info="starting HTTP server on :3030"
ts=2020-04-05T03:20:50.176181101Z caller=git.go:105 component=gitchartsync info="starting sync of git chart sources"
ts=2020-04-05T03:20:50.196104439Z caller=release.go:140 component=release release=openfaas targetNamespace=openfaas resource=openfaas:helmrelease/openfaas helmVersion=v3 error="chart unavailable: mkdir /tmp/v3: read-only file system"
ts=2020-04-05T03:20:50.19935877Z caller=git.go:308 component=gitchartsync info="started mirroring new remote" remote=git@github.com:org/repo mirror=git@github.com:org/repo
panic: mkdir /tmp/flux-gitclone645854802: read-only file system

goroutine 86 [running]:
github.com/fluxcd/flux/pkg/git.(*Repo).step(0xc0000fca20, 0x1cd4cc0, 0xc00086af00, 0x1cd4c00)
	/home/circleci/go/pkg/mod/github.com/fluxcd/flux@v1.17.2-0.20200121140732-3903cf8e71c3/pkg/git/repo.go:306 +0xadf
github.com/fluxcd/flux/pkg/git.(*Repo).Start(0xc0000fca20, 0xc0000168a0, 0xc0005505b0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/fluxcd/flux@v1.17.2-0.20200121140732-3903cf8e71c3/pkg/git/repo.go:395 +0xd0
created by github.com/fluxcd/flux/pkg/git.(*Mirrors).Mirror
	/home/circleci/go/pkg/mod/github.com/fluxcd/flux@v1.17.2-0.20200121140732-3903cf8e71c3/pkg/git/mirrors.go:83 +0x276
```

**Additional context**
Add any other context about the problem here, e.g 
- Helm Operator image: docker.io/fluxcd/helm-operator:1.0.0-rc9
- Helm Operator chart version: 0.7.0
- Targeted Helm version: `version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}`
- Kubernetes version: `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:17:09Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by aditsachde** [comment]
Disabled the pod security policy, container was able to successfully run. It seems to not be a helm operator issue, and I don't really know if there's a better way for the operator to handle this issue.

I know this is probably not the best place to ask, but why would changing the required fsGroup of a container cause `/tmp` to become unwritable anyways? It would be good to know.
